CONFIG
  ENV
    MS_MAP_PATTERN "^/.*$" # Permite carregar mapfiles de qualquer caminho (útil para testes)
    # Define o nível de detalhe do log (5 é o máximo, ideal para depuração)
    MS_ERRORFILE "/maps/mapserver.log"
    MS_DEBUGLEVEL "1"
  END
  MAPS
    # Se quiser, você pode criar aliases para seus mapas aqui
  END
END